# Generated by Django 4.0.2 on 2022-12-11 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bakery',
            fields=[
                ('bakery_id', models.AutoField(primary_key=True, serialize=False)),
                ('Ingredients', models.CharField(choices=[('milk', 'milk'), ('egg', 'egg'), ('sugar', 'sugar')], max_length=100)),
                ('iteam_name', models.CharField(default=0, max_length=100)),
                ('Ingredients_quantity', models.CharField(choices=[('milk', '80%_milk'), ('egg', '40%_egg'), ('sugar', '90%_sugar')], max_length=100)),
                ('cost_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=0, max_length=100)),
                ('phoneNumber', models.CharField(default=0, max_length=10)),
                ('address', models.CharField(default=0, max_length=200)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bakery')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
