# Generated by Django 4.0.2 on 2022-12-11 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_remove_bakery_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery',
            name='Ingredients',
            field=models.CharField(choices=[('milk', 'milk'), ('egg', 'egg'), ('sugar', 'sugar')], default='milk', max_length=100),
        ),
        migrations.AddField(
            model_name='bakery',
            name='Ingredients_quantity',
            field=models.CharField(choices=[('milk', '80%_milk'), ('egg', '40%_egg'), ('sugar', '90%_sugar')], default='50%_sugar', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
